### ISSUE TITLE
Tournament Admin Features

### ISSUE THREAD

**Issue by shannonjanehogan** [sjhogan2/debate-sort#51]
- [ ] Tournament checklist

- [ ] Equity (similar to web app features- can we use same code?) 

- [ ] Form to calculate awards needed

- [ ] Auto room booking 

- [ ] See which volunteers have signed up, how many missing

- [ ] See who has paid/registered/who is missing 

- [ ] See complaints/equity
